language: minimal

services:
    - docker

jobs:
    include:
        - stage: Pull request
          if: type = pull_request
          script: docker build --pull --tag typescript-service .

        - stage: Build, Test, and Push
          if: type = push AND branch = master
          script:
              docker build --pull --tag typescript-service .
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              # - docker push app

        - stage: Deploy
          language: go
          go:
              - 1.13.3
          before_script:
              - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
              - go get sigs.k8s.io/kind
              - kind create cluster
              - kubectl cluster-info --context kind-kind
          script:
              - kubectl get all
          after_script:
              - kubectl delete cluster

        - stage: Dependency Updates
          if: type = cron AND branch = master
          script:
              - docker build --tag npm-dependency-updater --file Dockerfile.updater .
              - docker run --rm -v $PWD:/app -e GITHUB_TOKEN=$GH_TOKEN -e GITHUB_ORG=jamestalton -e CREATE_PR=true npm-dependency-updater
