language: minimal

services:
    - docker

jobs:
    include:
        - stage: Pull request
          if: type = pull_request
          script: docker build --pull --tag typescript-service .

        - stage: Build, Test, and Push
          if: type = push AND branch = master
          script:
              docker build --pull --tag typescript-service .
              # - docker push app

        # - stage: Deploy
        #   if: type = push AND branch = master
        #   script:
        #       - echo Deploy here

        - stage: Dependency Updates
          if: type = cron AND branch = master
          script:
              - docker build --tag npm-dependency-updater --file Dockerfile.updater .
              - docker run --rm -v $PWD:/app -e GITHUB_TOKEN=$GH_TOKEN -e GITHUB_ORG=jamestalton -e CREATE_PR=true npm-dependency-updater
