apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: $APP_NAME
    labels:
        app: $APP_NAME
spec:
    # tls:
    #   - hosts:
    #       - ${APP_NAME}.default.${KS_REGION}.containers.appdomain.cloud
    #       - ${KS_AKAMAI_DOMAIN}
    #     secretName: ${KS_CLUSTER_SUBDOMAIN}
    rules:
        - http:
              paths:
                  - path: $APP_INGRESS_PATH
                    pathType: Prefix
                    backend:
                        serviceName: $APP_NAME
                        servicePort: $APP_PORT
