apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: $NAME
    namespace: $NAMESPACE
    labels:
        app: $NAME
        version: $VERSION
data:
    # tls.crt: <base64_encoded_cert>
    # tls.key: <base64_encoded_key>
    username: YWRtaW4=
    password: MWYyZDFlMmU2N2Rm
