name: build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - run: docker build --tag docker.pkg.github.com/jamestalton/typescript-service/typescript-service:latest .

            - name: Docker Login
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com

            - run: docker push docker.pkg.github.com/jamestalton/typescript-service/typescript-service:latest

            - name: Get the TAG
              id: get_tag
              run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

            - name: TAG
            run: echo $TAG
              env:
                  TAG: ${{ steps.get_tag.outputs.TAG }}
