name: build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Docker Build
              run: docker build --tag docker.pkg.github.com/jamestalton/typescript-service:latest .

            - name: Docker Login
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com

            - name: Docker Push
              run: docker push docker build --tag docker.pkg.github.com/jamestalton/typescript-service:latest .
