name: build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    schedule:
        - cron: '*/15 * * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Git
              run: |
                  git config --global user.name "${GITHUB_ACTOR}"
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

            - name: Setup Node.js 12.x
              if: ${{ github.event_name != 'pull_request' }}
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 12.x

            - name: Update Dependencies
              if: ${{ github.event_name == 'schedule' }}
              run: |
                  rm -rf package-lock.json node_modules
                  npx npm-check-updates -u
                  npm install
                  npm audit fix
                  if git diff --name-only | grep 'package.json\|package-lock.json'; then
                      echo "Dependencies updated"
                  else
                      echo "No dependency updates available"
                      exit 0
                  fi
                  git add -u :/
                  git commit -m "fix(deps): update dependencies"

            - name: Update Version
              if: ${{ github.event_name != 'pull_request' }}
              run: |
                  npm version patch

            - name: Docker Build
              if: ${{ github.event_name != 'pull_request' }}
              run: |
                  VERSION=v`cat package.json | jq -r .version`
                  docker build --build-arg VERSION --tag docker.pkg.github.com/jamestalton/typescript-service/typescript-service:latest .

            - name: Git Push
              if: ${{ github.event_name != 'pull_request' }}
              run: |
                  VERSION=v`cat package.json | jq -r .version`
                  git push
                  git push origin $VERSION

            - name: Docker Push
              if: ${{ github.event_name != 'pull_request' }}
              run: |
                  echo ${{ secrets.GITHUB_TOKEN }} | docker login -u "${GITHUB_ACTOR}" --password-stdin docker.pkg.github.com
                  docker push docker.pkg.github.com/jamestalton/typescript-service/typescript-service:latest
                  VERSION=v`cat package.json | jq -r .version`
                  docker tag docker.pkg.github.com/jamestalton/typescript-service/typescript-service:latest docker.pkg.github.com/jamestalton/typescript-service/typescript-service:$VERSION
                  docker push docker.pkg.github.com/jamestalton/typescript-service/typescript-service:$VERSION
