name: build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Docker Login
              run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker Build
              run: docker build --tag jamestalton/typescript-service .

            - name: Build and push Docker images
              uses: docker/build-push-action@v1.1.0
              with:
                  username: jtalton
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  repository: jamestalton/typescript-service
                  tag_with_ref: true
                  push: ${{ startsWith(github.ref, 'refs/tags/') }}
