name: push

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Update Version
              run: |
                  curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
                  sudo apt-get install -y nodejs
                  git config --global user.name "${GITHUB_ACTOR}"
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
                  npm version patch

            - name: Docker Build
              run: |
                  VERSION=v`cat package.json | jq -r .version`
                  docker build --build-arg VERSION --tag docker.pkg.github.com/jamestalton/typescript-service/typescript-service:latest .

            - name: Git Push Version and Tag
              run: |
                  VERSION=v`cat package.json | jq -r .version`
                  git tag VERSION                
                  git push

            - name: Docker Push
              run: |
                  echo ${{ secrets.GITHUB_TOKEN }} | docker login -u "${GITHUB_ACTOR}" --password-stdin docker.pkg.github.com
                  docker push docker.pkg.github.com/jamestalton/typescript-service/typescript-service:latest
                  VERSION=v`cat package.json | jq -r .version`
                  docker tag docker.pkg.github.com/jamestalton/typescript-service/typescript-service:latest docker.pkg.github.com/jamestalton/typescript-service/typescript-service:$VERSION
                  docker push docker.pkg.github.com/jamestalton/typescript-service/typescript-service:$VERSION
