name: release

on:
    release:
        types:
            - published

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - run: docker build --tag docker.pkg.github.com/jamestalton/typescript-service/typescript-service:${{ github.event.release.tag_name }} .

            - name: Docker Login
              run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com

            - run: docker push docker.pkg.github.com/jamestalton/typescript-service/typescript-service:${{ github.event.release.tag_name }}

            - run: docker tag docker.pkg.github.com/jamestalton/typescript-service/typescript-service:${{ github.event.release.tag_name }} docker.pkg.github.com/jamestalton/typescript-service/typescript-service:latest

            - run: docker push docker.pkg.github.com/jamestalton/typescript-service/typescript-service:latest
